### PR TITLE
Fixing docker image

### PR DESCRIPTION
**Pull request by vzhilin-nc**
Docker image missing cryptominisat5 executable.

### CODE REVIEW

**Comment by msoos** [comment]
Ah, good point, thank you so much for the pull! Also, let me know if you need any functionality, I'd be happy to implement it if it seems interesting :)

**Comment by vzhilin-nc** [comment]
Thanks! I would like to ask you about some good books to start learning
block cipher analysis techniques.

вт, 5 фев 2019, 13:47 Mate Soos notifications@github.com:

**Comment by msoos** [comment]
A classic, Applied Cryptography, is good :)  Also, I have heard good things about Serious Cryptography. Otherwise, the CRYPTO and EUROCRYPT conferences are really good. Good luck!

**Comment by vzhilin-nc** [comment]
Thank you very much!

сб, 9 февр. 2019 г. в 00:21, Mate Soos <notifications@github.com>:

**Pull request merged**
